apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: avengers
  labels:
    run: grafana
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 
    nodePort: 31011
  selector:
    app: grafana
