apiVersion: v1
kind: Service
metadata:
  name: smpprj-c
  namespace: avengers
  labels:
    run: smpprj
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30007
  selector:
    app: smpprj
