apiVersion: v1
kind: Service
metadata:
  name: monitoring-app
  namespace: avengers
  labels:
    run: monitoring-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31006
  selector:
    app: monitoring-app
