apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sonarqube
  namespace: avengers
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: mahi4847/sonar_avengers:latest
        ports:
        - containerPort: 80
