apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: avengers
  labels:
    run: sonarqube
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30025
  selector:
    app: sonarqube
