apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: avengers
  name: prometheus-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
